name: Nrupatunga
url: http://nrupatunga.github.io
baseurl: https://github.com/nrupatunga/nrupatunga.github.io
destination: ./_site
twitter: nrupatunga1987
lsi: false
port: 4000
markdown: kramdown
future: true
kramdown:
  parse_block_html: true
  syntax_highlighter: rouge
permalink: pretty
#paginate: 5
google_analytics: UA-107715197-1
gems:
  - jekyll-sitemap

exclude:
  - .travis.yml
  - validate.rb
  - README.md
  - Gemfile
  - Gemfile.lock
  - bower_components
  - update-vendor-deps.sh
  - vendor/bundle
  - vendor/bower.json
