# Dependencies
markdown:  redcarpet
redcarpet:
  extensions: ["tables"]

highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            NRUPATUNGA
tagline:          'Computer Vision & Machine Learning Enthusiast'
description:      'This is my personal website, where you can find out what am I currently doing in my life. <br><br>I write articles on Computer Vision, Machine Learning and Deep Learning with a good mixture of theory and hands on.' 
author:
  name:           'Nrupatunga'

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           github.com/nrupatunga

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
  - jekyll-paginate
